export const Colors = {
  primary: '#a04100',
  primaryContainer: '#ff6b00',
  onPrimary: '#ffffff',
  onPrimaryContainer: '#572000',
  surface: '#fcf9f8',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerLow: '#f6f3f2',
  surfaceContainer: '#f0eded',
  surfaceContainerHigh: '#eae7e7',
  surfaceContainerHighest: '#e5e2e1',
  onSurface: '#1c1b1b',
  onSurfaceVariant: '#5a4136',
  outline: '#8e7164',
  outlineVariant: '#e2bfb0',
  tertiary: '#0062a1',
  tertiaryContainer: '#059eff',
  onTertiary: '#ffffff',
  secondary: '#5f5e5e',
  secondaryContainer: '#e2dfde',
  onSecondary: '#ffffff',
  onSecondaryContainer: '#636262',
  error: '#ba1a1a',
  errorContainer: '#ffdad6',
  inverseSurface: '#313030',
  inverseOnSurface: '#f3f0ef',
  inversePrimary: '#ffb693',
};

export default Colors;
